services:
  frankframework:
    image: frankframework/frankframework:latest
    ports:
      - "8080:8080"
    configs:
      - source: resources_yml
        target: /opt/frank/resources/resources.yml
    volumes: &frank-volumes
      - {{CONFIGURATIONS_DIR}}:/opt/frank/configurations
    environment:
      instance.name: FrankFlowApp
  frank-flow:
    image: frankframework/frank-flow:latest
    build: .
    ports:
      - "8081:8080"
    volumes: *frank-volumes
    environment:
      configurations.directory: /opt/frank/configurations

configs:
  resources_yml:
    content: |
      jdbc:
        - name: "frankflowapp"
          type: "org.h2.jdbcx.JdbcDataSource"
          url: "jdbc:h2:mem:test;NON_KEYWORDS=VALUE;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;TRACE_LEVEL_FILE=0;"
